### ISSUE TITLE
Improve debug mode performance

### ISSUE THREAD

**Issue by casey** [cberner/redb#156]
Initializing a large redb database in debug mode is much slower than release mode.

On my machine it takes around 9 seconds to initialize a 50 GiB database in debug mode, but 0.7 seconds to initialize the same size database with `--release`.

I'm wondering if there's some optimization that's being done in `--release` mode which could be manually implemented, to make debug mode faster.

**Comment by cberner** [comment]
Hmm, what use case do you have that needs debug mode, and have you tried changing the [opt-level](https://doc.rust-lang.org/cargo/reference/profiles.html#opt-level)?

**Comment by casey** [comment]
Because `--release` compile times are slower, I use debug mode while developing and running the tests.

**Comment by casey** [comment]
(Or, rather, I usually use debug mode, but because the tests are really slow in debug mode, I have to use release mode while working on `ord`, which makes the compile times worse.)

**Comment by cberner** [comment]
![flamegraph](https://user-images.githubusercontent.com/842688/152669989-de43b8d5-0cd2-49a0-bffe-ef35dba3cd5b.svg)

Doesn't look promising. Essentially all the time is spent in slice indexing and try_into(). I guess using unsafe might fix it, but that doesn't seem worth it. I'd guess all the bounds checking on slices is the issue, since it can't be optimized out in `-O0`

Sounds like 10-100x performance difference is expected too: https://nnethercote.github.io/perf-book/build-configuration.html

Lemme know if you have ideas for speeding debug mode up though!

**Comment by casey** [comment]
Initializing a new database was the operation that was particularly slow, so it might be worth profiling that specifically.

**Comment by cberner** [comment]
Yep, that's what I did. That profile is just for initializing a 50GB db. The bottom call on the flamegraph is `Storage::new` which is called from `Database::open`

**Comment by casey** [comment]
Ah, gotcha. Yeah, then no clever ideas. I'm super surprised that it's all slice indexing. In that case there's probably nothing very clever to be done.

**Comment by cberner** [comment]
@casey this should be fast now. Between https://github.com/cberner/redb/pull/219 & https://github.com/cberner/redb/pull/221 I can now initialize a 50GB database in < 96ms, even in debug mode :)
