### ISSUE TITLE
maybe can add benchmark with mdbx ?

### ISSUE THREAD

**Issue by gcxfd** [cberner/redb#265]
https://gitflic.ru/project/erthink/libmdbx
https://docs.rs/libmdbx/latest/libmdbx/

libmdbx is superior to legendary [LMDB](https://symas.com/lmdb/) in terms of features and reliability, not inferior in performance. In comparison to LMDB, libmdbx make things "just work" perfectly and out-of-the-box, not silently and catastrophically break down. The list below is pruned down to the improvements most notable and obvious from the user's point of view.

Up to 30% faster than LMDB in [CRUD](https://en.wikipedia.org/wiki/Create,_read,_update_and_delete) benchmarks.

Benchmarks of the in-[tmpfs](https://en.wikipedia.org/wiki/Tmpfs) scenarios, that tests the speed of the engine itself, showned that libmdbx 10-20% faster than LMDB, and up to 30% faster when libmdbx compiled with specific build options which downgrades several runtime checks to be match with LMDB behaviour.

**Comment by cberner** [comment]
Thanks for pointing me to mdbx. It looks like a nice upgrade on lmdb. I've decided not to benchmark against it at this time, because it has less adoption than lmdb and seems to be architecturally similar. Right now I'm only interested in adding new databases to my benchmarks, if they are significantly different than the existing set (e.g. rocksdb).
I see there's a project, [ioarena](https://github.com/pmwkaa/ioarena), for benchmarking different embedded key-value stores. I think adding redb there is preferable.
