### ISSUE TITLE
Non-cryptographic checksum collisions could lead to corruption

### ISSUE THREAD

**Issue by DemiMarie** [cberner/redb#298]
ReDB assumes that a partial write will cause checksum verification to fail.  However, the checksum is not a collision-resistant hash, so this is not a valid assumption at least in theory.

**Comment by cberner** [comment]
That's true in theory, and certainly there could be malicious attacks that cause a collision. However, the hash used is XXH3 in 128bit mode, and from what I understand of XXH3 it is well tested and provides statistically uniform hashes, so in practice I do not expect this to be a problem. Do you know of any cases where this would fail in practice, for non malicious workloads?

**Comment by DemiMarie** [comment]
The problem is that workloads might be able to be made malicious.  Consider a program that exposes ReDB’s key-value API over a network, analogous to memcached or Redis.  This would then be an exploitable vulnerability.

If a cryptographic hash such as Blake3 is too slow, another option would be to use Poly1305, which is a fast cryptographic one-time-MAC.  Provided that the data to be written to disk is known with certainty before the key is written to disk, even an attacker with read-only access to the database file would not be able to cause a falsely-correct checksum.  Doing so would require changing the data to be written _after_ the key is known.  This does not provide any authentication of the on-disk data, but it does guarantee integrity against accidental corruption.

**Comment by cberner** [comment]
I see, ya good point. It seems difficult to craft that exploit, since the attacker would also need fine grained control over the order in which the page cache is flushed. I admit this is more practical than I had thought though. I'll think about it some more.

Blake3 would definitely hurt performance. I tried it when I was prototyping this feature. Poly1305 sounds interesting, but the benchmarks I've found look like it would be slow: https://kerkour.com/rust-symmetric-encryption-aead-benchmark & https://www.bearssl.org/speed.html both suggest it's on the order of 1-2GB/s. Does that sound right to you?

**Comment by DemiMarie** [comment]
An optimized assembler implementation can be less than 0.5 cycles per byte, so at least 4GB/s.  Are you referring to just Poly1305, or to ChaCha20-Poly1305?  You do not need the latter unless you want to support encryption at rest (itself useful).

**Comment by DemiMarie** [comment]
From a performance perspective, I think there is _much_ more that can be done.  For instance, a thread-per-core design (using Glommio or similar) combined with direct I/O, batching of transactions (to amortize the cost of `fsync()`), and a userspace buffer pool can be far faster than anything based on `mmap()`.

**Comment by cberner** [comment]
Just Poly1305. Ya, unfortunately 4GB/s is likely too slow. XXH3's throughput is ~50GB/s on my computer, and even at that rate there's a ~25% slow down in raw throughput for the single phase commit with checksum approach

**Comment by cberner** [comment]
I thought through the malicious message workload you brought up, and it's definitely possible in theory. 

The scenario would be something like:
```
table.insert(malicious_key, malicious_value);
table.insert(good_key, good_value);
txn.commit();
```
and the attacker wants the transaction to appear as:
```
table.insert(malicious_key, malicious_value);
txn.commit();
```
To do this they need to:
1) control the order in which pages are flushed to disk, so that the ones related to `good_key` are never written
2) introduce a crash during, or immediately before, the fsync() operation
3) ensure that the checksums for the partially written data are valid

With complete control over the workload, or read access to the database file (3) is possible, since XXH3 is not collision resistant. However, it requires the attacker to have knowledge of the database contents, because the input to the checksum includes many other values (all the other keys in the b-tree root, along with their child node numbers)

The docs already note that a non-cryptographic checksum is used, but I'll make them a bit more clear on this point. 

Since this requires the attacker to combine multiple other exploits to execute this attack, I still think this is largely theoretical and that the performance hit from using a collision resistant checksum is not worthwhile.

Happy to reconsider though, if there's a practical scenario where this could be exploited, that I've missed

**Comment by DemiMarie** [comment]
> Just Poly1305. Ya, unfortunately 4GB/s is likely too slow. XXH3's throughput is ~50GB/s on my computer, and even at that rate there's a ~25% slow down in raw throughput for the single phase commit with checksum approach

That is definitely annoying!  I wonder if part of that is because of memory bandwidth limitations or increased cache misses.

**Comment by casey** [comment]
> Happy to reconsider though, if there's a practical scenario where this could be exploited, that I've missed

This seems hard to exploit, but one possible scenario to think about is if redb is used on a physical device that must remain secure, if if an attacker has some level of physical access. For example inside a secure enclave, or a tamper-resistant embedded device.

In this scenario an attacker might be able to precisely control the order of operations performed by redb and be able to make the device crash. Additionally, if the precise hardware is known to the attacker, then the attacker may be able to know the order that pages will be flushed.

**Comment by cberner** [comment]
Ah yes, that does seem plausible. I'll add a note recommending that anyone worried about malicious input use the 2PC commit option

**Comment by casey** [comment]
That looks great!

This makes me wonder, are any of the common cryptographic hardware extensions fast enough to be useful? Either cryptographic hash functions, like SHA-2, or ciphers, like AES. I think in you can use ciphers to construct hash functions and MACs.

**Comment by cberner** [comment]
From what I know of AES-NI, it's only like a 2x speedup or so. The [BLAKE3 benchmarks](https://github.com/BLAKE3-team/BLAKE3) show it against SHA-256 and SHA-256 is way slower. It says it was run on a Cascade Lake server, so that should definitely have the AES extension

**Comment by casey** [comment]
Ahh, bummer.
