### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by repi** [cberner/redb#300]
Would it be possible to add support for Windows for this crate also? 

It looks like currently the issue is that it uses raw unix file handles for the memory mapping with [`std::os::unix::io::AsRawFd`](https://crates.io/crates/memmap2), so may need to switch to a platform-independent version like `memmap2` crate for the memory mapping operations.

We've been interested in replacing our lmdb usage (and likely sled also) with redb and this is currently the main blocker.

**Comment by cberner** [comment]
Ya, it'll probably take me a bit, since I'm unfamiliar with Windows APIs and am currently focused on stabilizing the file format.

I want to keep the dependencies of this crate to a minimum so am reluctant to add `memmap2`, but if you'd like to contribute a PR with Windows support that doesn't add a new dependency, I'd be happy to take it

**Comment by xsxz01** [comment]
I also want to support Windows
