### ISSUE TITLE
Random suggestions for shorter names

### ISSUE THREAD

**Issue by casey** [cberner/redb#339]
I have a some random suggestions for shorter names for some types. These are really personal preference, but I thought it would be worth proposing to see what you thought:

```
AccessGuard -> Guard
DatabaseBuilder -> Builder
DatabaseStats -> Stats
MultimapTable -> Multimap
MultimapTableDefinition -> MultimapDefinition
ReadOnlyMultimapTable -> ReadOnlyMultimap
ReadableMultimapTable -> ReadableMultimap
```

**Comment by cberner** [comment]
Oops, I never replied here, sorry!

`DatabaseBuilder -> Builder` ya, I like this suggestion and it seems consistent with `std::thread::Builder`.

I prefer the longer `MultimapTable` names because `Multimap` sounds to me like it should be a trait or a user space data structure like `HashMap`.

I'm not sure about `AccessGuard -> Guard`. I named it that way after `std::sync` which names them `MutexGuard`, `RwLockReadGuard`...etc.

Ya, I don't really like the name `DatabaseStats`, but I'm not sure `Stats` is better. I feel like maybe it should be called `DatabaseInfo`, `DebugInfo` or something like that. Any idea whether there's a common term among other databases?

**Comment by cberner** [comment]
Ok, well lmdb & postgres both use the term "stats", so "stats" it is :) I'm going to keep `DatabaseStats` though, at least for now, since I may add a `TransactionStats` to help debug why a transaction was slow
