### ISSUE TITLE
Increase maximum size of existing DB

### ISSUE THREAD

**Issue by bruwozniak** [cberner/redb#407]
Let's say I have a Database that I created with max size of 100GB, but it turns out that the needed space for the data is actually a bit higher.

Given the database can grow dynamically, is there a way to increase the maximum capacity of an existing database?

Rebuilding the existing data would take a few days so it would be great if it can be avoided...

**Comment by cberner** [comment]
Unfortunately not. The maximum size is used to calculate a fixed size header, so dynamic growth can only grow up to the maximum size

**Comment by Kerollmops** [comment]
I don't know how redb and LMDB differ on this point, but [LMDB can change the max size when a database is open a second time](http://www.lmdb.tech/doc/group__mdb.html#gaa2506ec8dab3d969b0e609cd82e619e5). If the size is set to something smaller than the current size, it is silently set to the current size. Otherwise, the max size can be changed to something bigger, and the database will continue to grow.

As a small piece of advice for @bruwozniak, if you can, the best thing to do would probably be to set the exact volume size as the max size. I hope redb tries to do its best to reuse pages. LMDB is _kind of_ bad toward this point and will try to allocate new pages (for speed?) instead of reusing the freed ones.

**Comment by cberner** [comment]
Interesting, I'll have to read up on how lmdb does that. I should probably change the file format to support changes to the max db size.

Unfortunately using the max volume size would break Windows at the moment. dynamic growth isn't supported on Windows currently, due to limitations of their mmap API.

**Comment by doki23** [comment]
I have some simple thoughts:
1. put head in an independent file and record max size
2. when start it up with a new max size, load the old one, and overwrite with the new head
