### ISSUE TITLE
Potential speedup from userspace cache

### ISSUE THREAD

**Issue by casey** [cberner/redb#483]
I wanted to open an issue to discuss a potential speedup from using a userspace cache.

Bitcoin transaction outputs are often spent soon after they're created, so we got a very nice speedup by:

- Adding a hashmap of outputs to ordinal ranges
- Reading from the hashmap before trying the database
- Writing to the hashmap instead of the database
- Flushing the hashmap on commit, and only committing every 5000 blocks

Could redb's userspace cache wind up giving the same or similar performance boost, without needing to do anything except commit less frequently?

If writes to redb's userspace cache are only written to disk on commit, and reads try the cache before hitting the database, then this might give a similar speedup.

**Comment by casey** [comment]
I thought of this because we recently had a [big performance regression](https://github.com/casey/ord/issues/1166).

There were three commits which looked suspicious. One of them was the change from redb 0.10.0 to 0.11.0, but I benchmarked the latest code with redb 0.10.0, and it's still slow, so it doesn't look like that's it.

The other two commits introduced writes to the database between the final flush on commit, so my thinking is that by adding a bunch of writes mid-commit, they undid the performance improvements we got by only writing on flush.

This made me think that perhaps, with the userspace cache, such writes might not affect performance, if they only get persisted to disk on commit.

**Comment by cberner** [comment]
> If writes to redb's userspace cache are only written to disk on commit, and reads try the cache before hitting the database, then this might give a similar speedup.

It already does that, as long as the cache doesn't get full.

The current implementation may or may not give a similar speedup to your HashMap though. It [currently](https://github.com/cberner/redb/blob/master/src/tree_store/page_store/cached_file.rs#L70) caches `Vec<u8>` which are usually the same size as an OS page. It only flushes them to disk during a durable commit. However, the OS page cache is allowed to do the same thing (it doesn't have to write to disk until you fsync), so it'd be a bit surprising if the userspace cache was a lot faster here.

I would guess that the speedup you're getting from the HashMap is from better data locality: the hot data is all in the HashMap and you don't have GBs of cold data mixed in like the redb table has

In theory, the userspace cache could be much more granular. Instead of storing whole pages, I could store the keys & values directly into a `HashMap` or `BtreeMap` like you're doing. That would be more complicated to implement though, because then higher level parts of the code base would need to deal with it

**Comment by casey** [comment]
> It already does that, as long as the cache doesn't get full.

NIce.

> However, the OS page cache is allowed to do the same thing (it doesn't have to write to disk until you fsync), so it'd be a bit surprising if the userspace cache was a lot faster here.

Could the depth of the trees be a factor here? The database tree has a large number of pages, whereas the userspace cache would be much shallower.

> I would guess that the speedup you're getting from the HashMap is from better data locality: the hot data is all in the HashMap and you don't have GBs of cold data mixed in like the redb table has

In that case, wouldn't the userspace cache have the same good locality properties as the hashmap?

**Comment by cberner** [comment]
> Could the depth of the trees be a factor here? The database tree has a large number of pages, whereas the userspace cache would be much shallower.

I don't think so, the OS page cache doesn't need to store a tree for cache look-ups because it can leverage virtual memory addresses, so if anything it would be faster than the userspace cache. Think of the userspace cache as a Rust implementation of the OS page cache, that is it maps addresses (file offset ranges) to `Vec<u8>`

> In that case, wouldn't the userspace cache have the same good locality properties as the hashmap?

No, because the userspace cache is caching pages and not key-value pairs. Each page is ~4kB worth of key-value pairs, whereas your HashMap is caching just the individual pairs. The pages contain key-value pairs in ascending order, so unless your hot data is all adjacent (by RedbKey sort order) the pages will be polluted with cold data

**Comment by casey** [comment]
> I don't think so, the OS page cache doesn't need to store a tree for cache look-ups because it can leverage virtual memory addresses, so if anything it would be faster than the userspace cache. Think of the userspace cache as a Rust implementation of the OS page cache, that is it maps addresses (file offset ranges) to `Vec<u8>`

I might be misunderstanding, but when you do a read on a redb table, won't the tree that it has to consult be deeper, because it has all the pages in it, whereas if you do a read on the userspace cache, it will be shallower, because it only contains dirty or recently read pages?

> No, because the userspace cache is caching pages and not key-value pairs. Each page is ~4kB worth of key-value pairs, whereas your HashMap is caching just the individual pairs. The pages contain key-value pairs in ascending order, so unless your hot data is all adjacent (by RedbKey sort order) the pages will be polluted with cold data

Ah, okay, makes sense, and now I understand what you meant by:

> In theory, the userspace cache could be much more granular. Instead of storing whole pages, I could store the keys & values directly into a HashMap or BtreeMap like you're doing. That would be more complicated to implement though, because then higher level parts of the code base would need to deal with it

That might be a good future change. Obviously modulo how complicated the implementation is. I suspect that temporal locality is common in many workloads, e.g. values you inserted recently are more likely to be read/changed than values you inserted a long time ago.

**Comment by cberner** [comment]
> I might be misunderstanding, but when you do a read on a redb table, won't the tree that it has to consult be deeper, because it has all the pages in it, whereas if you do a read on the userspace cache, it will be shallower, because it only contains dirty or recently read pages?

No because the userspace cache is a cache on top of the `File`, so when you read from a `Table` it reads from the userspace cache, which in turn reads from the file if needed. The userspace cache is operating at the same level as the OS page cache, not doing caching above the redb table like your `HashMap` does.

**Comment by casey** [comment]
Ahhhh, okay, got it. Makes sense.

**Comment by cberner** [comment]
Ok, I thought this through and I don't think an additional cache at the key-value level would make sense. It's best if users implement that when they need it. It'd be somewhat complex, and also the performance trade offs are quite unclear. For small keys/values it might hurt performance because it would need to convert them into `Vec<u8>` for storage. Whereas at the application level the user can store the `u64` or whatever directly
