### ISSUE TITLE
Add VFS abstraction

### ISSUE THREAD

**Issue by rklaehn** [cberner/redb#560]
We would like to use redb in an environment where there is no access to a file system.

Sqlite defines a virtual file system https://www.sqlite.org/vfs.html . Maybe something similar but quite a bit simpler could be done for redb.

**Comment by cberner** [comment]
Have you tried patching the `PagedCachedFile` struct? I'm not familiar with the details of Sqlite's VFS, but that's probably similar

**Comment by dignifiedquire** [comment]
Following up on this, I started looking into what it would take, and got this branch going https://github.com/dignifiedquire/redb/tree/feat-file-abstraction

The good news: the surface are of the API is quite small overall, as you can see here: https://github.com/dignifiedquire/redb/blob/feat-file-abstraction/src/file.rs

The bad news: because this goes all the way through, if I want to avoid boxing, the generic ends up invading everywhere. 

Would love to hear your thoughts about if there is a direction of this that you would consider merging eventually.

**Comment by cberner** [comment]
If it requires a new generic parameter everywhere, I won't want to merge that.

If boxing doesn't add noticable overhead, I'd be open to considering that. I'd like to hear more about the proposed use cases though to be sure this is valuable enough to warrant adding support to redb, vs people just patching `PagedCachedFile` in their own fork
