### ISSUE TITLE
Persistent Savepoint, Savepoint vs. ReadTransaction?

### ISSUE THREAD

**Issue by ricochet1k** [cberner/redb#574]
I've been prototyping a distributed clustered database with redb as the internal data store, and the two features I've found myself wanting are:
- Being able to save Savepoints to disk and restore them on open somehow
- On commit of a WriteTransaction, turn it into a ReadTransaction at the same point.

I'm also not quite sure what the difference is between a ReadTransaction and a Savepoint is at the implementation level. My best understanding is that both must hang on to the root of the B-tree and prevent its children from being overwritten, right? Would it make sense to merge their API or allow transforming between them?

Other than Savepoint persistence, I think I can just implement my own `commit` with something like:
```rust
wtx.commit()?;
let rtx = db.begin_read()?;
let wtx = db.begin_write()?;
let savepoint = wtx.savepoint()?;
```

But I can't help but wonder if there's a more efficient or ergonomic API than having a read transaction and a savepoint open at every recent synchronized step between the members of the cluster.

**Comment by cberner** [comment]
Sounds like a cool project!

Hmm, persisting savepoints to disk is an interesting idea. I'd require a pretty major change to how their implemented, and how redb's MVCC works. Can you tell me more about the use case for persisting them to disk?

`On commit of a WriteTransaction, turn it into a ReadTransaction at the same point.` I think the following code should be equivalent. Do you want to turn a `WriteTransaction` into a `ReadTransaction` at commit for convenience, or do you need some additional isolation guarantee?
```
wtx.commit()?;
let rtx = db.begin_read()?;
```

Yes, both `ReadTransaction` and `Savepoint` hold a reference to the btree root. However, `Savepoint` holds a bunch of additional state so that it can efficiently perform the `restore_savepoint()` operation. I don't think merging them would make sense, because then `ReadTransaction` would be much more expensive to construct.
