### ISSUE TITLE
lifetimes of the iterators returned by redb too stringent

### ISSUE THREAD

**Issue by mastercyb** [cberner/redb#579]
[cozodb](https://github.com/cozodb/cozo) is really cool db. and i believe redb and cozo are really important to each other as they could lay the foundation of a very powerful and efficient software. cozodb currently support five databases, but none of them are satisfy both performance and embeddability.

i asked creator to implement redb integration and the answer was that [lifetimes of the iterators returned by redb too stringent](https://github.com/cozodb/cozo/issues/79#issuecomment-1528756924).

not sure what this means, but i decided link these two issues to increase likelyhood that cozodb redb marry sometimes
especially in the face of [stabilization milestone](https://github.com/cberner/redb/issues/575)

**Comment by cberner** [comment]
I'm going to need more information. Please provide an example of the lifetime error, or the lifetimes on the redb API that you need.

**Comment by abdolence** [comment]
@cberner I have a similar issue, trying to integrate redb and future::stream async style iteration. For that, I need to store in this kind of structure (I simplified this example):

```
struct ListDocsStream<'a> {
    table_id: String,
    read_tx: ReadTransaction<'a>,
    table: ReadOnlyTable<'a, &'static str, &'static [u8]>,
    range: Range<'a, &'static str, &'static [u8]>,
}

impl<'a> ListDocsStream<'a> {
    fn new(table_id: String, redb: &'a redb::Database) -> Result<Self> {
        let td: TableDefinition<&str, &[u8]> = TableDefinition::new(table_id.as_str());
        let read_tx = redb.begin_read()?;
        let table = read_tx.open_table(td)?;
        let range = table.iter()?;

        Ok(Self {
            table_id,
            read_tx,
            table,
            range,
        })
    }
}
```
and it turned out I can't initialise something like this, and I haven't found any good workaround. Any advice would be appreciated. I suspect this may not be even possible without `unsafe` which isn't an option for me.

**Comment by cberner** [comment]
I don't think that's going to work. Range borrows `table` and Table borrows `read_tx`, so you're going to end up with a self referential struct which is not allowed in Rust

**Comment by abdolence** [comment]
Well, this definitely won't work :) 
I just gave an example to show the problem with creating an async iterator based on redb iterator.

**Comment by olebedev** [comment]
Hey @abdolence, have you found the workaround for it? :D I struggle with the exactly the same issue.

**Comment by olebedev** [comment]
Hi @cberner, what is the blessed approach to implement iterators that are based on the `redb::Range`?

**Comment by olebedev** [comment]
For example, I have the following code that doesn't work:

```rust
struct OpLogIterator<'a, K: Kind> {
    id: UUID,
    buffer: Vec<u8>,
    phantom: PhantomData<K>,
    table: Table<'a, ChunkKey, ChunkValue>,
    range: Range<'a, ChunkKey, ChunkValue>,
}

impl<'a, K: Kind> OpLogIterator<'a, K> {
    fn new(id: UUID, txn: &'a WriteTransaction) -> Self {
        let start = ChunkKey::new(id, u64::MAX);
        let table: Table<'a, ChunkKey, ChunkValue> = txn.open_table(OP_LOG_TABLE).unwrap();
        let range: Range<'a, ChunkKey, ChunkValue> = table.range(start..).unwrap();
        Self {
            id,
            phantom: PhantomData,
            table,
            range,
            buffer: Vec::new(),
        }
    }
}
```

While this one would work for sure:
```rust
struct OpLogIterator<'a, K: Kind> {
    id: UUID,
    buffer: Vec<u8>,
    phantom: PhantomData<K>,
    range: Range<'a, ChunkKey, ChunkValue>,
}

impl<'a, K: Kind> OpLogIterator<'a, K> {
    fn new(id: UUID, range: Range<'a, ChunkKey, ChunkValue>) -> Self {
        Self {
            id,
            phantom: PhantomData,
            range,
            buffer: Vec::new(),
        }
    }
}
```
But this is a leaked abstraction, because a part of the logic will live outside the `new` fn, in particular, the `redb::Range` have to be created and kept alive outside the `new` logic.

What would be the best way to structure this part while have a signature like
```rust
let mut iter = OpLogIterator::new(id, txn);
```

**Comment by abdolence** [comment]
@olebedev 
I don't believe there is a good solution without changing Redb (or introducing weird additional tasks/channels), and those are probably requires a lot of changes inside. As a result I just gave up on the idea to use it this way. In my case I could read all data into memory (not as efficient as I was hoping for, indeed). 

PS. Though I didn't follow any changes since then so can't say anything for the recent versions.

**Comment by cberner** [comment]
`ReadOnlyTable` returns a `Range` with the `'static` lifetime. So if you can use that it may work. It's not possible with a `Table`.

**Comment by olebedev** [comment]
@cberner, thanks, this seems to work!

My idea behind using `WriteTransaction` was to create a single write-transaction for _anything_ that is related to an atomic change in the application context, including occasional reads. Meaning, if I have written something down I expect this data to be available for reads _within_ the top-level `WriteTransaction`.

Is there a way to structure my application so intermediate results of `WriteTransaction` can be read along with having these `Range`es with `'static` lifetimes?

**Comment by cberner** [comment]
No, that's not supported

**Comment by olebedev** [comment]
@cberner, understood. Do you think it's reasonable to add this capability? If so, would you be willing to accept PRs?

**Comment by cberner** [comment]
No, I don't see a way to implement this in redb's architecture. 
You should think of a Table like a BtreeMap. So if it's not possible with BtreeMap then it's likely not possible with a Table.
