### ISSUE TITLE
Unwraps & asserts - there might be a better way

### ISSUE THREAD

**Issue by thedodd** [cberner/redb#622]
Hello @cberner, thanks for all of the work on this project. Really stoked to see an alternative to sled which is alive and kicking. 

I am interested in using this project in a project of my own. Looking through the code base a bit, I've noticed pretty heavy use of unwrap and a fair number of asserts. I've filtered out tests, benches, examples and the like.

Firstly, I totally get that. In many cases, the invariant is clear, and the unwrap will not panic. Other cases are not as trivial to reason about (as a newcomer to the code base).

However, this gives me a bit of pause about adoption. The primary difficulty with unwrap/expect/assert and friends, is that as soon as you use them, you forfeit the type system's ability to encode the real state of the system. Invariants which were once true may no longer be true after some refactoring, and you no longer have the type system to prove/encode that.

In essence, relying on unwraps to this degree essentially require much more rigorous testing, and a lot of that testing is going to be pushed onto the users of the code (me).

All of that said, I think this is somewhat common for a new-ish project. It takes time to refine error handling patterns, time to craft types to encode the invariants of the system instead of relying on unwraps. My bias is probably clear on this front: I wish panics were only minimally used, if ever, and only as part of a failure condition to start programs (throughout Rust ecosystem). IMHO, everything should be gracefully handled up to the point that an exit is required. Basically these things all look like landmines to me (mostly joking) `:)`.

What do you think about this? Do you have plans to refine this aspect of the code? Or perhaps you are quite alright with unwrap generally speaking? I am more than happy to discuss more, and if time/life permits, I would love to help out on this front as well.

**Comment by cberner** [comment]
Ya, I'd like to limit the number of `unwrap()` calls. I've found them & the assertions to be pretty helpful when used to assert cases that would otherwise result in data corruption, and that has made fuzzing quite effective. But not having them at all would be ideal.

Ya there are a bunch that should be removed, like [this one](https://github.com/cberner/redb/blob/376d38a817f38781359c541071687d178441ec8b/src/tree_store/btree_base.rs#L24-L26) which has a TODO to that effect. If you have time to contribute. That'd be welcome! Feel free to send PRs for small changes. If you have a bigger change in mind, probably best to open a draft / issue to discuss it first.

**Comment by cberner** [comment]
Closing, but feel free to send PRs
