### ISSUE TITLE
Provide a way to test if a database file needs repair before opening it

### ISSUE THREAD

**Issue by veryordinally** [cberner/redb#639]
For large redb database files, the repair performed when opening a database that has not been shut down cleanly takes a long time (often more than 30 minutes for the ordinals index when running with `--index-sats`). We can't currently warn the user that a repair is necessary, so we often have users assuming `ord` hangs and then killing the process.

What would be the best way to see if `mem.needs_repair()` is true for a given database file before calling `Database::new`?

**Comment by cberner** [comment]
Oh hmm, interesting issue. I don't really want to expose `needs_repair()` since that's pretty low level functionality. Maybe some kind of callback on `DatabaseBuilder` like `DatabaseBuilder::set_repair_callback(callback: impl Fn() -> bool)` which would take a callback and allow the user to abort the repair (causing `new` to fail with a error). Although I'm a little reluctant to jump into adding that right away, since it seems like there might be other functionality people might want when getting a repair callback

As a quick hack you can just check the the recovery bit in the file yourself. Now that the format is stable, that won't change without a minor/major version bump. I do that in the tests. It's the 9th byte 2nd bit. https://github.com/cberner/redb/blob/d8be9580591aa063469df6a7faf243d17a5a59a6/src/tree_store/page_store/header.rs#L593-L597

**Comment by veryordinally** [comment]
Thanks for quick reply, that all makes sense. Will go with checking the bit for now.

**Comment by cberner** [comment]
Can you give the attached PR a try and see if that addresses your use case?
