### ISSUE TITLE
Cursor API

### ISSUE THREAD

**Issue by onbjerg** [cberner/redb#683]
## Motivation

As mentioned in #673, the iterator API is nice for scanning an entire table, but does not provide you a way to arbitrarily reposition where in the queried range you are.

The iterators are double ended, and calling `next` moves an internal left page forward, while calling `next_back` moves an internal right page backwards. This means that it is not possible to get the previous element in an iterator.

It is also not possible to arbitrarily reposition the iterator. In some use cases, you might scan a large range, skip a portion of the range, or go back. For these scenarios, it is only possible to skip a portion of the range, but it is inefficient since it ends up iterating all pages that you want to skip.

The solution would be to add cursors, preferably an immutable one (for just reading) and a mutable one (for manipulating pages).

As an example, reth makes heavy use of cursors, and we have another concept for an iterator (called a "walker", but logically similar).

## Proposal

redb is based on `BTreeMap`'s API, and there is currently plans to add a cursor API, which is available in nightly: https://github.com/rust-lang/rust/issues/107540

On top of the public API in that proposal, I would like the cursors to have some additional functionality:

- The ability to reseek to the first element in the table (`first`)
- The ability to reseek to the last element in the table (`last`)
- The ability to seek to a specific key (we call this `seek_exact`, the cursor will not move if the key is not found)
- The ability to seek to a key less or greater than a given key. In our API this is called `seek` and is somewhat equivalent to opening a new cursor in the RFC above with e.g. `lower_bound` or `upper_bound`

**Comment by cberner** [comment]
Thanks for the additional details. I see how this is fundamentally different from an iterator now.

Do you want this functionality for convenience or because you expect it to improve performance?

While not as convenient, I think all of these functions can be achieved by calling `range()` again on the original table from which an iterator was retrieved.

**Comment by onbjerg** [comment]
I think it's mostly for convenience but I would also expect there to be a small performance gain vs. calling `range` every time. How much, I'm not sure. To implement the functionality above we would need to keep track of what we are currently pointing to ourselves, and call `range(..)` every time, which will do 2 searches (one for the left page and one for the right page), correct?

**Comment by cberner** [comment]
yes, although that could probably be optimized, so that it lazily performs the searches. Would take a bit of work to refactor it, but I think it would work.

Ya, the convenience makes sense. I think you should be able to prototype that on top of the existing API. Want to do that, and then I can take a look at how it worked out for you?

**Comment by cberner** [comment]
Gonna close this for now, but feel free to re-open it after `std` has stabilized its interface and I'll take another look
