### ISSUE TITLE
Encoding and decoding error

### ISSUE THREAD

**Issue by hummingly** [cberner/redb#736]
Right now decoding will panic for most types, especially ones that have more invariants to upkeep like str (https://docs.rs/redb/latest/src/redb/types.rs.html#356-386). Would it be possible to return an error instead?

I am asking because I want to use a binary format like [khonsulabs/pot](https://github.com/khonsulabs/pot) and upon failing to deserialize a struct, because of a few missing fields as an example, return the more loosely typed value as an error when possible. This would make it easier to deal with user crash reports. Furthermore, most binary formats use serde as data model, so serialize and deserialize return a `Result` anyway.

Sadly, this would be a breaking change as it would require to change the return type of as_bytes and from_bytes from the RedbValue trait. However, it should be fine for StorageError as it non-exhaustive. I imagined the API to be similar to the heed crate where the error type is Box<dyn Error> which would allow casting (https://docs.rs/heed/latest/heed/enum.Error.html).

**Comment by cberner** [comment]
Unfortunately, I don't think that would work well. `AccessGuard` would then have to return a `Result` instead of the value directly: https://github.com/cberner/redb/blob/213e67550eab19364daf14df710a621bd6cab16d/src/tree_store/btree_base.rs#L150

Are you able to implement your table for `Result<T>` instead of `T`? I haven't tried that, but it seems like it could work in your case
