### ISSUE TITLE
Random thoughts about optimizations

### ISSUE THREAD

**Issue by casey** [cberner/redb#744]
- LMDB has a mode where you append to a table, and it doesn't do key comparisons except for with the previous highest key, and the append fails if the key isn't higher than the previous highest key. I don't think it's actually super useful for ord, since I don't think we spend much time doing key comparisons, but it's interesting.

- We have some tables where the keys are contiguous integers, starting at 0, and entries in the table are never removed. Is there an optimization here that would allow avoiding storing keys? Or an optimization which is possible because values are never removed?

- We tried to create a super large table where the overhead from redb wound up being prohibitive. Is there a way to avoid this overhead somehow? We could do somewhat inconvenient things like guarantee we were only appending, only do bulk inserts, never remove keys, etc, if it could reduce the overhead.

**Comment by cberner** [comment]
> LMDB has a mode where you append to a table, and it doesn't do key comparisons except for with the previous highest key, and the append fails if the key isn't higher than the previous highest key. I don't think it's actually super useful for ord, since I don't think we spend much time doing key comparisons, but it's interesting.

That'd be easy to add. I'd want to see a convincing use case with benchmarks showing it's valuable though. It seems like a weird API

> We have some tables where the keys are contiguous integers, starting at 0, and entries in the table are never removed. Is there an optimization here that would allow avoiding storing keys? Or an optimization which is possible because values are never removed?

What type is the value?

> We tried to create a super large table where the overhead from redb wound up being prohibitive. Is there a way to avoid this overhead somehow? We could do somewhat inconvenient things like guarantee we were only appending, only do bulk inserts, never remove keys, etc, if it could reduce the overhead.

What are the key & value types?

**Comment by casey** [comment]
> > We have some tables where the keys are contiguous integers, starting at 0, and entries in the table are never removed. Is there an optimization here that would allow avoiding storing keys? Or an optimization which is possible because values are never removed?
> 
> What type is the value?

The values are big tuples:

```rust
pub(crate) type InscriptionEntryValue = (
  u16,                // charms
  u64,                // fee
  u32,                // height
  InscriptionIdValue, // inscription id
  i32,                // inscription number
  Option<u32>,        // parent
  Option<u64>,        // sat
  u32,                // sequence number
  u32,                // timestamp
);
```

> > We tried to create a super large table where the overhead from redb wound up being prohibitive. Is there a way to avoid this overhead somehow? We could do somewhat inconvenient things like guarantee we were only appending, only do bulk inserts, never remove keys, etc, if it could reduce the overhead.
> 
> What are the key & value types?

The keys are `[u8; 32]` and the values are `&[u8]`. Value sizes are from 100 bytes to 100,000 bytes.

**Comment by cberner** [comment]
> The values are big tuples:
> 
> ```rust
> pub(crate) type InscriptionEntryValue = (
>   u16,                // charms
>   u64,                // fee
>   u32,                // height
>   InscriptionIdValue, // inscription id
>   i32,                // inscription number
>   Option<u32>,        // parent
>   Option<u64>,        // sat
>   u32,                // sequence number
>   u32,                // timestamp
> );
> ```

Eliding the keys isn't going to make a big difference. I assume they're u32 or something, so 4bytes? The page pointer and checksum in the internal branch pages are much larger, 64bit and 128bit respectively: https://github.com/cberner/redb/blob/d8be9580591aa063469df6a7faf243d17a5a59a6/docs/design.md#branch-page

I might be able to optimize the packing of redb's internal pages since you're inserting in sorted order. I'll give that some thought.

Since it looks like your value is fixed width. I would move those out of redb into a flat file. You could store the latest key in redb, so you know the length of valid data in your file, and then doing lookups in that file is simply multiplying the value width by the index you want to read and doing a seek.

> The keys are `[u8; 32]` and the values are `&[u8]`. Value sizes are from 100 bytes to 100,000 bytes.

Interesting. Do the keys have any structure to them, or are they effectively random bytes? Do you know the distribution of value lengths? Or at least the mean length?

**Comment by casey** [comment]
Sorry, I spaced and never responded to this!

> Eliding the keys isn't going to make a big difference. I assume they're u32 or something, so 4bytes? The page pointer and checksum in the internal branch pages are much larger, 64bit and 128bit respectively: https://github.com/cberner/redb/blob/d8be9580591aa063469df6a7faf243d17a5a59a6/docs/design.md#branch-page

Makes sense! Are the checksums unused if not doing the checksum commit strategy?

> Since it looks like your value is fixed width. I would move those out of redb into a flat file. You could store the latest key in redb, so you know the length of valid data in your file, and then doing lookups in that file is simply multiplying the value width by the index you want to read and doing a seek.

Yeah, that's probably what we need to do. It's annoying not to have the simplicity of a single database to work with.

> Interesting. Do the keys have any structure to them, or are they effectively random bytes? Do you know the distribution of value lengths? Or at least the mean length?

The keys are random bytes, since they're transaction IDs, and the values are bitcoin transactions, so really they have minimal structure.

**Comment by cberner** [comment]
No worries!

The checksums are still there and are used by the `check_integrity()` method. For a while they were only in the file when the checksum commit strategy was used, but I decided it complicated the code too much and this way the user can switch between commit strategies at will.

> The keys are random bytes, since they're transaction IDs, and the values are bitcoin transactions, so really they have minimal structure.

I can't think of much to optimize then. Even removing the checksums wouldn't help much, since the values are so large. And there's no duplication of values in redb, so nothing is being wasted there. There is a fair bit of empty space in the file because when a node in the tree splits it creates two half filled nodes. I'm pretty sure that's all zero initialized, so you could try storing it on a compressed filesystem
