### ISSUE TITLE
Add new intermediate durability mode

### ISSUE THREAD

**Issue by rklaehn** [cberner/redb#751]
We are using redb in https://github.com/n0-computer/iroh. I am unable to get sufficient performance for my use case.

It seems that it would be helpful to have an additional durability mode. If I understand correctly, the current durability modes are as follows:

Paranoid: fsync all the time, be paranoid
Immediate: write to disk, and then call fsync (sync_data)
Eventual: no difference to immediate, at least on unix. eventual flag is ignored, sync_data is called in any case. See https://github.com/cberner/redb/blob/master/src/tree_store/page_store/file_backend/unix.rs#L68C19-L68C28
None: the data will remain the mem page cache and not go to disk at all.

What I would be hoping for would be a way to get redb to write all data to the file system, but *not* call sync_data or sync_all. So leave the data in the OS file system cache, but don't force the OS to write the data to the actual storage immediately.

I had hoped that Durability::Eventual would do that, but it does not. See above.

Is there a way to get this behaviour? I think it is a decent compromise between performance and durability. Once the data is in the hands of the OS it is visible from other processes, and it is safe against an app crash. Only an OS crash or a power outage would lead to data loss.

This would be equivalent to the sqlite setting pragma synchronous=OFF, https://www.sqlite.org/pragma.html#pragma_synchronous , which is *not* the same as Durability::None in redb.

**Comment by cberner** [comment]
Sorry, but I don't want to support a feature that can lead to data
corruption.

**Comment by marvin-j97** [comment]
> Eventual: no difference to immediate, at least on unix. eventual flag is ignored, sync_data is called in any case

@rklaehn I think I've been bitten by this issue as well in my [Rust storage engine benchmark](https://github.com/marvin-j97/rust-storage-bench). The docs say:

> Commits with this durability level have been queued for persitance [sic!] to disk

I thought "Eventual" durability would return immediately and asynchronously fsync the data, like Sled does by default. This allows a bit of data loss (up to 500ms for Sled), but that may be acceptable for many workloads, given the huge performance boost it gives (especially on non-PLP disks).

In my [LSM-based storage engine](https://github.com/fjall-rs/fjall), I allowed doing both, eventual durability like Sled (default), and also allow manually calling `persist` to call fsync/fdatasync after every insert or batch, depending on the workload.

The change in performance is obviously dramatic:

On consumer-grade non-PLP:

![image](https://github.com/cberner/redb/assets/33938500/d0fc0460-0279-4973-92f6-d7f127421f89)

(redb runs for a longer time, because it takes ~75 seconds to setup the initial test data, the latency jumps up because at that point it has to serve writes & reads at the same time)

On PLP SSD:

![image](https://github.com/cberner/redb/assets/33938500/a19b1a65-7c14-4ab6-9c07-58a20f37617b)

> Sorry, but I don't want to support a feature that can lead to data
corruption.

Data loss != data corruption ideally.

**Comment by cberner** [comment]
It's not quite the same as sled, but if you can accept data loss but not data corruption. Then `Durability::None` is what you want. You probably want to use that and then use `Durability::Immediate` every say 500ms

**Comment by rklaehn** [comment]
> Sorry, but I don't want to support a feature that can lead to data corruption.

Fair enough. It's a bit of a can of worms.

You can emulate this behaviour by doing a wrapper for StorageBackend that intercepts sync_data and just calls flush when eventual is true, but as you said you might then get data corruption on OS crash or power outage, just like in sqlite. So maybe just having a custom storage backend for this use case is good enough.

> It's not quite the same as sled, but if you can accept data loss but not data corruption. Then `Durability::None` is what you want. You probably want to use that and then use `Durability::Immediate` every say 500ms

I actually tried this but saw some unexpected behaviour. I have a benchmark where I do lots of small transactions with Durability::None and then one empty transaction with Durability::Immediate. But what I saw was that the database file was becoming extremely large with this approach.

Another issue with this approach is that your write cache might get full before the regular transaction with Durability::Immediate. So ideally you would watch the cache size and flush on demand, but I did not see a way to do this.

**Comment by rklaehn** [comment]
> Data loss != data corruption ideally.

I think the issue is that the order in which the dirty pages in the OS page cache are being written to disk is basically random, so if you have a power outage or OS crash at just the right time you might get the database file in a weird state.
