### ISSUE TITLE
Feature request: Provide an automatic way to upgrade the format of file

### ISSUE THREAD

**Issue by wentao** [cberner/redb#925]
https://github.com/cberner/redb/blob/51ca54cd913a075a3bd0acd8793f198aa6e12c29/src/error.rs#L201

When we encounter this issue in production, it's tricky to walkaround it except deleting the old store entirely. This would cause all existing data lost.

**Comment by cberner** [comment]
There is example code for upgrading from v1 to v2: https://github.com/cberner/redb/issues/785

**Comment by wentao** [comment]
Thanks for the link. Is that example part of the redb repo? If redb format gets upgraded again in the future, would that example apply too? I was hoping the redb library can provide an way to upgrade the format automatically. This is especially important for things run in production.

**Comment by cberner** [comment]
Yes, the approach used in that example should work for future changes, because it reads the data using the public interface of the old version of redb and then writes using the newer redb.

Unfortunately, it was not feasible to provide an automatic upgrade between version 1 and version 2.

redb follows semvar versioning, so you can expect any changes in 2.x to provide automatic upgrades, but changes between 1.x and 2.x to require manual upgrade

**Comment by rsalmei** [comment]
Couldn't you at least add export/import like Sled does?
https://docs.rs/sled/latest/sled/struct.Db.html#method.export
